### PR TITLE
Made compatible with tensorflow 2.0.0-beta1

### PR DESCRIPTION
**Pull request by rednafi**
- Tested on tf 2.0.0-beta1
- Formatted with black code formatter for better readability (max line length=88 character)
- Replaced unused variables with ```_``` and added an explanation of the variable

### CODE REVIEW

**Comment by thushv89** [comment]
Appreciate the pull request. I will review this over the weekend and merge or let you know if any changes are required. Thanks.

**Comment by abhipn** [comment]
@thushv89 Any reason for not merging this pull request?

**Comment by John-8704** [comment]
@thushv89 Any reason for not merging this pull request yet?

**Comment by John-8704** [comment]
@thushv89 Any reason for not merging this pull request with master branch?

**Comment by ryzbaka** [comment]
There are a ton of unnecessary  modifications in the original file, try cleaning it up so that the library imports are the only things that are different from the original file to make  it compatible with tensorflow 2+.

**Comment by thushv89** [comment]
Thank you for the contribution. I do apologize sincerely for not being able to merge this PR. But I think all of these have been fixed in the stable `master` branch. 

One feedback for PRs, please make sure there are no IDE specific settings files committed (e.g. `.vscode/settings.json`). 

I'll be closing this one off. But if you see anything that's not fixed, please do contribute with a new PR. I apologize again for not merging this one sooner. :(

**Pull request closed without merging**
